[colors]
ansi = [
  '#45475a', #Surface 1 - Mocha
  '#f38ba8', #Red - Mocha
  '#a6e3a1', #Green - Mocha
  '#f9e2af', #Yellow - Mocha
  '#89b4fa', #Blue - Mocha
  '#f5c2e7', #Pink - Mocha
  '#94e2d5', #Teal - Mocha
  '#bac2de', #Subtext 1 - Mocha
]
background = '#1e1e2e' #Base - Mocha
brights = [
  '#585b70', #Surface 2 - Mocha
  '#f38ba8', #Red - Mocha
  '#a6e3a1', #Green - Mocha
  '#f9e2af', #Yellow - Mocha
  '#89b4fa', #Blue - Mocha
  '#f5c2e7', #Pink - Mocha
  '#94e2d5', #Teal - Mocha
  '#a6adc8', #Subtext 0 - Mocha
]
compose_cursor = '#f2cdcd' #Flamingo - Mocha
cursor_bg = '#f5e0dc' #Rosewater - Mocha
cursor_border = '#f5e0dc' #Rosewater - Mocha
cursor_fg = '#11111b' #Crust - Mocha
foreground = '#cdd6f4' #Text - Mocha
scrollbar_thumb = '#585b70' #Surface 2 - Mocha
selection_bg = '#585b70' #Surface 2 - Mocha
selection_fg = '#cdd6f4' #Text - Mocha
split = '#6c7086' #Overlay 0 - Mocha
visual_bell = '#313244' #Surface 0 - Mocha

[colors.indexed]
16 = '#fab387' #Peach - Mocha
17 = '#f5e0dc' #Rosewater - Mocha

[colors.tab_bar]
background = '#11111b' #Crust - Mocha
inactive_tab_edge = '#313244' #Surface 0 - Mocha

[colors.tab_bar.active_tab]
bg_color = '#cba6f7' #Mauve - Mocha
fg_color = '#11111b' #Crust - Mocha
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#181825' #Mantle - Mocha
fg_color = '#cdd6f4' #Text - Mocha
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#1e1e2e' #Base - Mocha
fg_color = '#cdd6f4' #Text - Mocha
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#313244' #Surface 0 - Mocha
fg_color = '#cdd6f4' #Text - Mocha
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#45475a' #Surface 1 - Mocha
fg_color = '#cdd6f4' #Text - Mocha
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'Catppuccin Org'
name = 'Catppuccin Mocha'
