# man 5 alacritty for the config docs
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true
[shell]
program = "/bin/zsh"
[env]
term = "xterm-256color"
[window]
opacity = 0.9
blur = false
decorations = "None"
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
resize_increments = true
[scrolling]
history=10000
multiplier=3
[font]
normal = {family = "VictorMono NFM", style = "Regular"}
bold = {family = "VictorMono NFM", style = "Bold"}
italic = {family = "VictorMono NFM", style = "Italic"}
bold_italic = {family = "VictorMono NFM", style = "Bold Italic"}
size = 11.25
[colors]
transparent_background_colors = true
[bell]
command="None"
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true
[cursor]
style = {shape = "Block", blinking = "Off"}
vi_mode_style = "None"
[mouse]
hide_when_typing = false
[keyboard]
bindings = [
    {key = "v", mods = "Super", mode = "Vi", action = "Paste"},
    {key = "c", mods = "Super", mode = "Vi", action = "Copy"},
]
[hints]
[debug]
